# fly.toml app configuration file generated for donkeyboard on 2023-05-16T19:23:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "donkeyboard"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
